export const ITEM_MAPPINGS = {
  // Common ores and ingots
  "iron ore": "IRON_ORE",
  "iron ingot": "IRON_INGOT",
  "steel ingot": "STEEL_INGOT",
  "starmetal ingot": "STARMETAL_INGOT",
  "starmetal ore": "STARMETAL_ORE",
  "orichalcum ore": "ORICHALCUM_ORE",
  "orichalcum ingot": "ORICHALCUM_INGOT",
  "silver ore": "SILVER_ORE",
  "gold ore": "GOLD_ORE",
  "platinum ore": "PLATINUM_ORE",
  "mythril ore": "MYTHRIL_ORE",
  asmodeum: "ASMODEUM",
  "void ore": "VOID_ORE",

  // Crafting materials
  charcoal: "CHARCOAL",
  "sand flux": "SAND_FLUX",
  "obsidian flux": "OBSIDIAN_FLUX",
  lodestone: "LODESTONE",
  "fae iron": "FAE_IRON",
  voidmetal: "VOIDMETAL",
  cinnabar: "CINNABAR",
  tolvium: "TOLVIUM",
  azoth: "AZOTH",

  // Leather and hides
  "thick hide": "THICK_HIDE",
  rawhide: "RAWHIDE",
  "coarse leather": "COARSE_LEATHER",
  "rugged leather": "RUGGED_LEATHER",
  "layered leather": "LAYERED_LEATHER",
  "runic leather": "RUNIC_LEATHER",
  "infused leather": "INFUSED_LEATHER",
  scarhide: "SCARHIDE",

  // Wood and lumber
  timber: "TIMBER",
  lumber: "LUMBER",
  "green wood": "GREEN_WOOD",
  "aged wood": "AGED_WOOD",
  wyrdwood: "WYRDWOOD",
  ironwood: "IRONWOOD",
  "glittering ebony": "GLITTERING_EBONY",
  petalcap: "PETALCAP",
  barbvine: "BARBVINE",

  // Fibers and cloth
  fiber: "FIBERS",
  fibers: "FIBERS",
  hemp: "HEMP",
  cotton: "COTTON",
  linen: "LINEN",
  sateen: "SATEEN",
  silk: "SILK",
  wirefiber: "WIREFIBER",
  silkweed: "SILKWEED",
  phoenixweave: "PHOENIXWEAVE",
  scalecloth: "SCALECLOTH",
  blisterweave: "BLISTERWEAVE",
  shadowcloth: "SHADOWCLOTH",

  // Food and reagents
  reagents: "REAGENTS",
  quintessence: "QUINTESSENCE",

  // Gems and dust
  "gemstone dust": "GEMSTONE_DUST",
  "pristine amber": "PRISTINE_AMBER",
  "pristine diamond": "PRISTINE_DIAMOND",
  "pristine emerald": "PRISTINE_EMERALD",
  "pristine ruby": "PRISTINE_RUBY",
  "pristine sapphire": "PRISTINE_SAPPHIRE",
  "pristine topaz": "PRISTINE_TOPAZ",
  "pristine amethyst": "PRISTINE_AMETHYST",
  "pristine aquamarine": "PRISTINE_AQUAMARINE",
  "pristine opal": "PRISTINE_OPAL",
  "pristine jasper": "PRISTINE_JASPER",
  "pristine onyx": "PRISTINE_ONYX",
  "pristine moonstone": "PRISTINE_MOONSTONE",
  "pristine carnelian": "PRISTINE_CARNELIAN",

  // Special items
  "voidbent ingot": "VOIDBENT_INGOT"
};

export const COMMON_ITEMS = [
  "Iron Ore",
  "Orichalcum Ore",
  "Starmetal Ore",
  "Steel Ingot",
  "Starmetal Ingot",
  "Charcoal",
  "Thick Hide",
  "Linen",
  "Fiber",
  "Lumber",
  "Timber",
  "Silk",
  "Rawhide",
  "Green Wood",
  "Aged Wood",
  "Silver Ore",
  "Gold Ore",
  "Mythril Ore",
  "Reagents",
  "Coarse Leather",
  "Rugged Leather",
  "Wyrdwood",
  "Ironwood",
  "Sand Flux",
  "Obsidian Flux",
  "Hemp",
  "Cotton",
  "Wirefiber",
  "Silkweed",
  "Iron Ingot",
  "Orichalcum Ingot",
  "Platinum Ore",
  "Lodestone",
  "Fae Iron",
  "Voidmetal",
  "Cinnabar",
  "Tolvium",
  "Azoth",
  "Quintessence",
  "Sateen",
  "Phoenixweave",
  "Runic Leather",
  "Layered Leather",
  "Glittering Ebony",
  "Asmodeum",
  "Void Ore",
  "Scalecloth",
  "Infused Leather",
  "Barbvine",
  "Blisterweave",
  "Scarhide",
  "Shadowcloth",
  "Voidbent Ingot"
];
